### ISSUE TITLE
佬 你的那个trojango用443端口 我还想加个博客如何操作 

### ISSUE THREAD

**Issue by H4CKE3** [jxj1994/hijk_script#1]

**Comment by jxj1994** [comment]
不好意思，这个项目是从源作者的项目fork出来作为备份存在的，我也不是原作者，你的问题我解答不了，我自己也没用过trojango，不过你这种需求我自己的经验用vless+ws+nginx会好处理点，只需要配置好nginx的反向代理规则就行，特定path走代理，其他访问请求正常处理到博客站点中

**Comment by H4CKE3** [comment]
谢谢 懂了我去了解了解你这种方法 我使用trojan是听说不容易封端口 不知道你这种方法怎么样
